# Generated by Django 6.0.6 on 2026-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('services', '0002_service_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Услуги, которые может проводить этот врач', to='services.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Миссия и ценности'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
    ]
