# Generated by Django 6.0.6 on 2026-06-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('pages', '0002_doctor_services_alter_companyinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.doctor', verbose_name='Врач'),
        ),
    ]
